name: Send mail
on: push

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello world
      run: echo "Hello World"

    - name: Sending a mail
      if: $ {{ always() }}
      uses: devellany/send-mailer@v1.0.2
  with:
    host: smtp.google.com
      # Optional port (defaults to 465)
      port: 465
      account: ${{secrets.ACCOUNT}}
      password: ${{secrets.MAIL_PASSWORD}}
      sender: devellany
      from: ${{secrets.MAIL_ADDRESS}}
      to: devellay@dico.me
      subject: mail title.
      body: your messages.
      # Optional content type (defaults to text/plain)
      contentType: text/plain
      # Optional attachment files (JSON type. require property 'path')
      attachments: '[{"path":"README.md"}]'